sudo: required
dist: xenial
language: python
install:
  - sudo apt-get install graphicsmagick libav-tools -y
  - pip install -r requirements.txt
  - python setup.py develop
  - avconv -version
  - avconv -help
python:
  - "2.7"
script:
  - gm -version
  - cd example && prosopopee
notifications:
  irc: "chat.freenode.net#prosopopee"
